### ISSUE TITLE
Add black auto transforming in pre-commit

### ISSUE THREAD

**Issue by egozverev** [mapaction/pipeline_mvp#41]
Currently black formatting is automatically checked as a park of flake8 checks.

I ran the following command:
```
$ pre-commit run --all-files
```
And received multiple `BLK100 Black would make changes` errors. After that I manually executed black transforms and the errors were gone:
```
$ docker compose run airflow black dags/ plugins/ tests/
```
@felnne, since we're anyway enforcing black code style why not to include black transformations in the pre-commit run?

**Comment by felnne** [comment]
@egozverev - in general the reason automatic fixes aren't applied is to ensure the user feels in control over what is happening to their code, rather than it being transformed once they try and commit.

Clearly what's happening will be visible afterwards, but I sort of feel this falls under the 'principle of least surprise', which I'd like to follow to ensure people feel comfortable with what's going on.

My solution to this problem specifically (running Black automatically) is to configure a [file watcher in PyCharm](https://black.readthedocs.io/en/stable/integrations/editors.html#pycharm-intellij-idea). That has the advantage of being something _I_ want to happen, whereas if we did this at the pre-commit hook level, _everyone_ would be opted-in.

If everyone would be happy for this to be an automatic thing then I'm open to it, but I think that's needs discussion and agreement by everyone.

As an aside - in the interests of keeping information in one place - it is probably best if issues all live in Jira where possible.

**Comment by egozverev** [comment]
That makes a lot of sense, thank you.
